name: Build and Push Multi-Arch "poorman-aws-playground" Docker Image
on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - '**'

jobs:
  docker-multiarch-build:
    uses: lesposito87/github-workflows/.github/workflows/docker-multiarch-build.yml@v1.0.0
    with:
      docker_repo: lesposito87/poorman-aws-playground
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
