name: Build and Push Multi-Arch "poorman-aws-playground" Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU (for ARM64 emulation)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Latest Tag from Docker Hub & Increment
        id: tag
        run: |
          REPO="lesposito87/poorman-aws-playground"
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=1" | jq -r '.results[0].name')

          # If no tags exist, default to v0.0.0
          if [[ "$LATEST_TAG" == "null" || -z "$LATEST_TAG" ]]; then
            LATEST_TAG="v0.0.0"
          fi

          # Extract major, minor, patch from vX.Y.Z
          VERSION=$(echo "$LATEST_TAG" | sed 's/v//')
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3)

          # Increment patch version
          NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: |
            lesposito87/poorman-aws-playground:latest
            lesposito87/poorman-aws-playground:${{ env.NEW_TAG }}
          platforms: linux/amd64,linux/arm64
